# Generated by Django 3.1.7 on 2021-03-26 18:29

from django.db import migrations
import image_upload.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=image_upload.models.upload_to),
        ),
    ]
